Update participate.md
USRSE/usrse24 pull request #13
Opened 2024-02-12 15:38 UTC by jsubida

## Description

Add content from [Google Doc](https://docs.google.com/document/d/1T1LkjQ-Ug38aPCo7gkV3tW5UOy4IJWor1ntp6LJxSGQ/edit?usp=sharing)

## Checklist:

- [ ] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2024-conference-planning-committee) to ask for content reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc  @jrgochan

2024-02-12 15:45 UTC, mrmundt requested changes
Can you please also make an "Important Dates" page under `About`? I left an example from last year in the repo: https://github.com/USRSE/usrse24/blob/main/pages/about/dates.tbd

2024-02-12 15:45 UTC, mrmundt commented on pages/participate/participate.md
> +- **Camera-ready submissions (Notebooks, Papers)**: August 9
Please add days of the week (e.g., "Friday, March 22"). The extra clarity never hurts!

2024-02-12 15:45 UTC, mrmundt commented on pages/participate/participate.md
> +Birds of a Feather sessions are expected to be informal, and ideally will include the audience’s participation. Sessions will last 90 minutes and take place in rooms that will accommodate approximate
Unnecessary comma
```suggestion
Birds of a Feather sessions are expected to be informal, and ideally will include the audience’s participation. Sessions will last 90 minutes and take place in rooms that will accommodate approximately 100 people. Organizers may choose to submit with all presenters determined at the time of submission or include a plan for finding BoF presenters upon acceptance. Submission template [here](https://docs.google.com/document/d/1W86USaI0euZOuwPJoeZfZaX-qxG_OjRTM3brHNxNIvM/edit?usp=sharing).
```

2024-02-12 15:45 UTC, mrmundt commented on pages/participate/participate.md
> +Tutorials will take place ahead of the conference in a virtual format, and be recorded, from September 30th to October 11th. Infrastructure to register participants and allow the hosts to run the tut
```suggestion
Tutorials will take place ahead of the conference in a virtual format (to be recorded) from September 30th to October 11th. Infrastructure to register participants and allow the hosts to run the tutorial via Zoom will be provided. Tutorials may be either 90 minutes or two 90 minute sessions with a 30 minute break in the middle. Please note that you ***MAY*** submit similar proposals for both a tutorial and a Learning Topic workshop if you would like to deliver the same content in person at the conference. Submission template [here](https://docs.google.com/document/d/1RljR4M2kEBZx36JmSNLrw0iL7P-cx3aoosYdnHJR8t4/edit?usp=sharing).
```

2024-02-12 16:24 UTC, jbteves-sandia commented on pages/participate/participate.md
> +- **BoFs, Workshops, and Tutorials**: Due March 22. Notifications April 26.
```suggestion
- **BoFs, Workshops, and Tutorials**: Due Friday, March 22. Notifications Friday, April 26.
```

2024-02-12 16:24 UTC, jbteves-sandia commented on pages/participate/participate.md
> +- **Papers and Notebooks**: Due May 20. Notifications June 27.
```suggestion
- **Papers and Notebooks**: Due Monday, May 20. Notifications Friday, June 28.
```
Note that I messed that up, I intended for it to be Friday.

2024-02-12 16:25 UTC, jbteves-sandia commented on pages/participate/participate.md
> +- **Posters and Talks**: Due June 3. Notifications July 3.
```suggestion
- **Posters and Talks**: Due Monday, June 3. Notifications Wednesday, July 3.
```

2024-02-12 16:25 UTC, jbteves-sandia commented on pages/participate/participate.md
> +- **Camera-ready submissions (Notebooks, Papers)**: August 9
```suggestion
- **Camera-ready submissions (Notebooks, Papers)**: Friday, August 9
```

2024-02-12 16:32 UTC, mrmundt commented
FYI - there was an incorrect setting on CircleCI that was preventing building changes from forks. I have changed that so all PRs _should_ get CircleCI previews now.

2024-02-14 14:30 UTC, mrmundt commented on pages/about/dates.md
> +- **Main Conference**: October 15-17, 2023, Albuquerque, NM
```suggestion
- **Main Conference**: October 15-17, 2024, Albuquerque, NM
```

2024-02-14 14:41 UTC, jbteves-sandia commented
Yes, please change to "view with link."

2024-02-15 17:32 UTC, jsubida commented
> Yes, please change to "view with link."

@jbteves-sandia @mrmundt Should I change `templates.tbd` to `templates.md` and update `navigation.yml`? 

https://github.com/USRSE/usrse24/blob/main/pages/participate/templates.tbd

2024-02-15 17:36 UTC, mrmundt commented
> > Yes, please change to "view with link."
> 
> @jbteves-sandia @mrmundt Should I change `templates.tbd` to `templates.md` and update `navigation.yml`?
> 
> https://github.com/USRSE/usrse24/blob/main/pages/participate/templates.tbd

No, not this time. The templates are linked in the call itself. It'll be less work to _not_ have a different page that repeats the same information as the Google docs.

2024-02-15 18:55 UTC, mrmundt approved these changes
Thank you!

2024-02-16 16:15 UTC, merged