Update Patrick's affiliation
USRSE/usrse24 pull request #64
Opened 2024-07-10 16:03 UTC by diehlpk

## Description

Update Patrick's affiliation to finalize the travel request.

## Checklist:

- [ ] (Committee Chairs Only) I have posted the link for the PR in the usrse slack (#usrse-2024-conference-planning-committee) to ask for content reviewers
- [ x] I have previewed changes locally
- [ x] I have updated the README.md if necessary

cc **ADD GITHUB HANDLES HERE**

2024-07-10 21:27 UTC, mrmundt requested changes
Your name+affiliation is listed twice - this page and https://github.com/USRSE/usrse24/blob/main/pages/organization/organization.md

2024-07-11 02:03 UTC, diehlpk commented
> Your name+affiliation is listed twice - this page and https://github.com/USRSE/usrse24/blob/main/pages/organization/organization.md

@mrmundt Good catch. I updated he second occurrence.

2024-07-12 20:19 UTC, diehlpk commented
@mrmundt Could you please have a look again?

2024-07-12 20:21 UTC, mrmundt approved these changes

2024-07-12 20:21 UTC, merged